[project]
name = "mbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "pypdf>=6.7.3",
    "soupsieve>=2.8.3",
    "typing-extensions>=4.15.0",
]
